from enum import Enum


class ConstructionAction(Enum):

    CREATE_FRAME = "CREATE_FRAME"

    SELECT_FRAME = "SELECT_FRAME"

    INSERT_MULLION = "INSERT_MULLION"

    INSERT_MOVABLE_MULLION = "INSERT_MOVABLE_MULLION"

    INSERT_SASH = "INSERT_SASH"

    SELECT_GLASS = "SELECT_GLASS"

    SELECT_HARDWARE = "SELECT_HARDWARE"

    SELECT_EXTENSION = "SELECT_EXTENSION"

    INSERT_CONNECTOR = "INSERT_CONNECTOR"

    INSERT_LIMITER = "INSERT_LIMITER"

    SAVE = "SAVE"

    MANUAL_REVIEW = "MANUAL_REVIEW"